import type { Metadata } from "next";
import Breadcrumb from "@/app/(public)/_components/Breadcrumb";
import Card from "@/app/(public)/_components/Card";
import Callout from "@/app/(public)/_components/Callout";

export const metadata: Metadata = {
  title: "Calculator & Content Disclaimer",
  description:
    "Important disclaimer regarding AP Teacher Desk calculators, pay fixation tools, and official order summaries.",
  alternates: { canonical: "/disclaimer" },
};

export default function DisclaimerPage() {
  return (
    <div className="mx-auto max-w-4xl space-y-6 pb-12 font-sans">
      <Breadcrumb items={[{ label: "Disclaimer" }]} />

      <section className="space-y-4">
        <h1 className="text-display text-ink font-bold tracking-tight">
          Calculator & Content Disclaimer
        </h1>
        <p className="text-body text-inkSoft text-lg leading-relaxed">
          Important notice regarding the accuracy, legal status, and intended use of information on AP Teacher Desk.
        </p>
      </section>

      <Card className="p-6 md:p-8 space-y-6 border-hair bg-paperRaised">
        <div className="space-y-3">
          <h2 className="text-card-title text-ink font-bold">1. Non-Government & Unofficial Status</h2>
          <p className="text-body text-inkSoft">
            AP Teacher Desk is a private, independent platform. It is <strong>NOT an official portal</strong> of the Government of Andhra Pradesh, the Department of School Education, or the AP Finance Department.
          </p>
        </div>

        <div className="space-y-3">
          <h2 className="text-card-title text-ink font-bold">2. Calculator Estimates & Mathematical Models</h2>
          <p className="text-body text-inkSoft">
            All calculations generated by our utility tools—including PRC pay fixation, income tax comparisons, DA arrears splits, leave encashment, and pension/gratuity estimates—are <strong>informational estimates only</strong>. While formulas are built to match official AP RPS 2022 rules and tax provisions, individual payroll circumstances, service breaks, or specific DDO adjustments may alter final official figures.
          </p>
        </div>

        <div className="space-y-3">
          <h2 className="text-card-title text-ink font-bold">3. No Financial or Legal Liability</h2>
          <p className="text-body text-inkSoft">
            Under no circumstances shall AP Teacher Desk or its maintainers be liable for financial discrepancies, tax penalties, pay fixation errors, or administrative decisions made based on outputs from this site. Always cross-check results with official gazette copies and your controlling office.
          </p>
        </div>

        <div className="space-y-3">
          <h2 className="text-card-title text-ink font-bold">4. PDF & Source Document Accuracy</h2>
          <p className="text-body text-inkSoft">
            For legal and official purposes, the original PDF documents available via GOIR or official government gazettes remain the sole authoritative texts. Tabular data, pay scales, and eligibility matrices are preserved in their original PDF format to prevent transcription errors.
          </p>
        </div>
      </Card>

      <Callout tone="warning" title="Mandatory Verification" aria-label="Disclaimer mandatory verification">
        <p>
          Always present your official calculations and bill forms to your DDO, MEO, DEO, or STO Treasury Officer for final verification and approval.
        </p>
      </Callout>
    </div>
  );
}
